const portfolioData = {
  name: "Arafi Buya",
  role: "Full-Stack Developer",
  tagline: "Building the web, one stack at a time.",
  bio: "Computer Engineering student, Year 2. Passionate about building full-stack web apps with the MERN stack. Currently leveling up through 100+ hours of real-world projects — soon expanding into Mobile App Development & Cyber Security.",
  avatar: "assets/profilee.png",
  social: {
    github: "https://github.com/rafauu329-dev",
    linkedin: "#",
    email: "mailto:rafauu329@gmail.com",
  },
  stats: [
    { label: "Projects Built", value: "4+" },
    { label: "Hours Coded",    value: "100+" },
    { label: "Tech Stack",     value: "MERN" },
  ],
  skills: [
    { name: "HTML & CSS",   level: 90 },
    { name: "JavaScript",   level: 80 },
    { name: "React.js",     level: 75 },
    { name: "Node.js",      level: 70 },
    { name: "Express.js",   level: 70 },
    { name: "MongoDB",      level: 65 },
    { name: "REST API",     level: 72 },
    { name: "JWT / Auth",   level: 65 },
  ],
  learning: ["React Native", "TypeScript", "Cyber Security", "Next.js"],
  projects: [
    {
      title: "Twitter Clone",
      description: "Full-stack social media app with JWT auth, tweet creation, user interactions, and dynamic feed rendering. Focused on REST API design and scalable backend architecture.",
      image: "assets/twitter-clone.png",
      tags: ["MongoDB", "Express", "React", "Node.js", "JWT", "REST API"],
      link: "",
      github: "#",
      deployed: false,
      featured: true,
    },
    {
      title: "Neo Store",
      description: "Full-stack CRUD product manager with REST APIs, React frontend, and MongoDB database. Clean UI for creating, updating, and deleting inventory.",
      image: "assets/neo-store.png",
      tags: ["MongoDB", "Express", "React", "Node.js"],
      link: "https://product-store-neo.onrender.com/",
      github: "#",
      deployed: true,
      featured: false,
    },
    {
      title: "Personal OS",
      description: "Web-based productivity dashboard. Modules for goal tracking, habit monitoring, financial overview, and daily focus — with local data persistence.",
      image: "assets/personal-os.png",
      tags: ["HTML", "CSS", "JavaScript"],
      link: "https://rafauu329-dev.github.io/Personal-Os/",
      github: "#",
      deployed: true,
      featured: false,
    },
    {
      title: "Chill Circle",
      description: "Browser-based party game platform with Truth or Dare, Spin the Wheel, and Hot Potato mini-games. Focused on dynamic game logic and engaging UI.",
      image: "assets/chill-circle.png",
      tags: ["HTML", "CSS", "JavaScript"],
      link: "https://rafauu329-dev.github.io/chill-circle/",
      github: "#",
      deployed: true,
      featured: false,
    },
  ],
  education: {
    degree: "Computer Engineering",
    year: "Year 2",
    course: "100 Hours MERN Bootcamp — Udemy",
  },
};